export const clientLinks: Record<string, { name: string; url: string; map?: boolean }> = {
  '01_cusezar.png': { name: 'Cusezar', url: 'https://cusezar.com/' },
  '02_hotel_city_bog_106.png': { name: 'Hotel City-Bog 106', url: 'https://www.google.com/maps/search/?api=1&query=Hotel+City+Bog+106+Bogota', map: true },
  '03_embajada_finlandia.png': { name: 'Embajada de Finlandia', url: 'https://finlandabroad.fi/web/col/pagina-principal' },
  '04_edificio_tierra_firme.png': { name: 'Edificio Tierra Firme', url: 'https://www.google.com/maps/search/?api=1&query=Edificio+Tierra+Firme+WSAP+Carrera+9+115+30+Bogota', map: true },
  '05_paloquemao.png': { name: 'Plaza de Paloquemao', url: 'https://plazadepaloquemao.com/' },
  '06_pintuco.png': { name: 'Pintuco', url: 'https://www.pintuco.com.co/' },
  '07_prosperidad_social.png': { name: 'Prosperidad Social', url: 'https://prosperidadsocial.gov.co/' },
  '08_embajada_polonia.png': { name: 'Embajada de Polonia', url: 'https://www.gov.pl/web/colombia/embajada' },
  '09_byd.png': { name: 'BYD', url: 'https://www.byd.com/co' },
  '10_industrias_argos.png': { name: 'Industrias Argos', url: 'https://petoutlet.com.co/' },
  '11_bulevar_42.png': { name: 'Bulevar 42', url: 'https://www.google.com/maps/search/?api=1&query=Bulevar+42+Plaza+Comercial+Carrera+13+41+36+Bogota', map: true },
  '12_artecma.png': { name: 'Artecma', url: 'https://artecma.com/' },
  '13_cafam.png': { name: 'Cafam', url: 'https://www.cafam.com.co/' },
  '14_argos.png': { name: 'Argos', url: 'https://colombia.argos.co/' },
  '15_sika.png': { name: 'Sika', url: 'https://col.sika.com/' },
  '16_cosechas.png': { name: 'Cosechas', url: 'https://www.cosechasexpress.com/' },
  '17_abril_constructora.png': { name: 'Abril Constructora', url: 'https://www.google.com/maps/search/?api=1&query=Abril+Constructora+Carrera+15+53+17+Bogota', map: true },
  '18_sodimac_homecenter.png': { name: 'Sodimac Homecenter', url: 'https://www.homecenter.com.co/' },
};
